# Site/SEO settings
email: admin@projectx.is
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: x
title: p r o j e c t x
description: >
  x
url: https://projectx.is
twitter_username: marklchaves
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/craigaustinFRSA
  - name: instagram
    url: https://www.instagram.com/Vimpt
  - name: github
    url: https://github.com/Projectx-hub/projectx
  - name: codepen
    url: https://codepen.io/marklchaves

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/dk-s_YAU0WZ

# Visual editor
_editor:
  default_path: /about/

# Formspree contact form integration not working at the moment. 
# Reverting to default Formcarry
# contact_form_action: https://formspree.io/mnqadrkp

# Submission settings
share_something_form_action: https://formspree.io/xgewkqae

# Disqus settings
disqus: projectxis

# MailChimp settings
#mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
#mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
# Moved to _data/authors.yml

# Map settings
google_maps_javascript_api_key: "AIzaSyCp4Olui9agnrGraMVWQnKUugyyXJG3RPI"

collections:
  help:
    output: true
    permalink: /:collection/:path/

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'x'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90 # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 320  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 480
    - width: 800
      quality: 90 # [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false # [Optional, Default: false]
  # Strip EXIF and other JPEG profiles. Helps to minimize JPEG size and win friends
  # at Google PageSpeed.
  strip: true # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: uploads # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/resized/%{width}/%{basename} # [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  save_to_source: false # [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %}
  # tags. See the "Caching" section of the README for more information.
  cache: false # [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
    - uploads/*/*/*/*.{jpeg,jpg}

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-responsive-image
#  - jekyll-srcset
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
